In [1]:
import numpy as np
print(np.__version__)

1.18.5


In [3]:
#how to craete numpy array
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
b=np.arange(10)
print(b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
l=list(range(1000))
%timeit [i**2 for i in l]

460 µs ± 49.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
l1=np.arange(1000)#array range
%timeit np.array(i**2 for i in l1)

4.37 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
#check dimension shape and length
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
3


In [13]:
c = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [1]:
#linspace function is used to linearly spaced data
#c = np.linspace(0,1,6)

In [3]:
import numpy as np
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
a=np.random.randint(0,20,15)
print(a)

[ 8 11  7 18 10 13 11 12  3 11 12 11  7  1  4]


In [5]:
#masking a numpy array
mask=(a%2==0)
print(mask)

[ True False False  True  True False False  True False False  True False
 False False  True]


In [6]:
print(a[mask])

[ 8 18 10 12 12  4]


In [9]:
mask=(a%2!=0)
a[mask]=-1
print(a)


[ 8 -1 -1 18 10 -1 -1 12 -1 -1 12 -1 -1 -1  4]


In [10]:
#it is possible to index array data in the form of interger index
a[[0,2,3,5,6]]=77
print(a)

[77 -1 77 77 10 77 77 12 -1 -1 12 -1 -1 -1  4]


In [13]:
a[[i for i in range(6)]]=77
print(a)
print(type(a))

[77 77 77 77 77 77 77 12 -1 -1 12 -1 -1 -1  4]
<class 'numpy.ndarray'>


In [14]:
a[[i for i in range(4)]]=111
print(a)

[111 111 111 111  77  77  77  12  -1  -1  12  -1  -1  -1   4]


In [16]:
#operations of numpy array
a=np.array([1,2,3,4,5])
print(a+1)

[2 3 4 5 6]


In [17]:
print(a**2)

[ 1  4  9 16 25]


In [18]:
a=np.ones((3,3),dtype='int') * 3;

In [19]:
b=np.diag([1,2,3])
print(a+b)

[[4 3 3]
 [3 5 3]
 [3 3 6]]


In [20]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a==b
np.array_equal(a,b)

True

In [21]:
a=np.array([1,0,1,0], dtype='bool')
a=np.array([1,0,1,0], dtype='bool')


In [22]:
#mathematical operations
a=np.arange(4)
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [28]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [24]:
x = np.array([[1,2], [3,4]])
print(x);

[[1 2]
 [3 4]]


In [25]:
x.sum()

10

In [26]:
x.sum(axis=0)#note 0 refers for column majaor order and 1 refers row major order 
#by default mode is column major order

array([4, 6])

In [29]:
a=np.array([1,2,3,4])
a.mean()


2.5

In [30]:
np.median(a)

2.5

In [31]:
a.std()

1.118033988749895

In [33]:
data=np.loadtxt('populations.txt')

In [35]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [36]:
data[:,0]

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [37]:
#current working dir
pwd

'C:\\Users\\richa soni'

In [38]:
year, hares, lynxes, carrots=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [42]:
population=data[:,1:]
np.argmax(population,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [46]:
#Boadcasting
a=np.array([[0,1,2]])
b=np.array([[0],[1],[2]])
print(a+b)
print(a-b)
print(a*b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [48]:
a=np.tile(np.arange(3),(3,3))
a

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [51]:
a=np.array([[1,2,3],[9,10,11]])
b=np.array([[6,7],[11,8]])
c=np.append(a,b,axis=1)
print(c)

[[ 1  2  3  6  7]
 [ 9 10 11 11  8]]


In [56]:
#new axis
#ravel function
#flatting data
a= np.array([[1,2],[3,4]])
print(a)
a=a[:,np.newaxis]
print(a.shape)
print(a.ndim)
print(a)

[[1 2]
 [3 4]]
(2, 1, 2)
3
[[[1 2]]

 [[3 4]]]


In [53]:

a=np.array(([1,2,3],[4,5,6]))
print(a.ravel())

[1 2 3 4 5 6]


In [55]:
#reshapeing is opposite to flatting
a=np.array([1, 2, 3, 4,5 ,6])
print(a)
a.reshape(3,2)

[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
#resize (fill empty places zero)
a=np.arange(4)
a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]
